### PR TITLE
Bashunit

### PR DESCRIPTION
**Pull request by Chemaclass**
## 📚 Description

Add [bashunit](https://bashunit.typeddevs.com/)

### CODE REVIEW

**Comment by dodie** [comment]
So far looks super! 👍  Just let me know when the PR is ready for review.

**Comment by Chemaclass** [comment]
With the release of [0.7](https://github.com/TypedDevs/bashunit/releases/tag/0.7.0), the installation and examples got simpler. Now you can review/merge it. Could you update the table on the README, @dodie?

**Comment by dodie** [comment]
Hi @Chemaclass ,

Sorry for the slow reply. The PR looks very promising so far! From my point of view, it's ready to be merged. If you agree, please convert the PR from draft to "ready for review".

Do you also plan to add other example tests, e.g. [assertion_showcase](https://github.com/dodie/testing-in-bash/blob/master/example-bash_unit/test/assertion_showcase.sh), [e2e_test](https://github.com/dodie/testing-in-bash/blob/master/example-bash_unit/test/e2e_test.sh), [setup_and_teardown](https://github.com/dodie/testing-in-bash/blob/master/example-bash_unit/test/setup_and_teardown.sh) or [unit test with strict mode](https://github.com/dodie/testing-in-bash/blob/master/example-bats/test/unit_test_strict.bats)?

Cheers,
Dávid

**Comment by Chemaclass** [comment]
We plan to finish the "snapshot assertions", and then we'll create a new release. Then we can merge this PR with the latest **bashunit** release. It might take some days, but latest I expect to have it ready by next week.

Would you suggest to add/change anything, @dodie? Just let us know :)

**Comment by Chemaclass** [comment]
We plan to add more test cases examples as you suggested, eg: assertion_showcase, e2e_test, setup_and_teardown, snapshot testing... We could do it in a follow up PR or in this one, as you prefer :)

**Comment by dodie** [comment]
Thanks! If it's not much hassle, I think it would be best to put it into this PR and merge them together. This would provide a more complete picture in the comparison. However, if it's more effort, just let me know and we can merge this PR as it already has useful info in it.

**Comment by Chemaclass** [comment]
Hy, @dodie ! Sorry for the lack of response/activity the last months. We have being pretty busy with other projects and we couldn't work on much on this one. I would suggest: let's merge this one now as it is, as it is bringing already clear value. And we will work on improving the examples and adding more, as soon as we find time (or anyone from the community). How does this sounds? :)

**Comment by dodie** [comment]
Hi @Chemaclass ,
Sounds like a plan! Let's move ahead and merge the PR. 👍

**Pull request merged**
